export const MANUFACTURER_RESULTS = 'MANUFACTURER_RESULTS';
export const MANUFACTURER_RESULT = 'MANUFACTURER_RESULT';
export const MANUFACTURER_CHARACTERS = 'MANUFACTURER_CHARACTERS';
export const EMAIL_SENT = 'EMAIL_SENT';
export const LOADING_MANUFACTURER = 'LOADING_MANUFACTURER';
export const LOADING_CHARACTERS = 'LOADING_CHARACTERS';